name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dlang: [dmd-latest, ldc-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dlang }}
      - name: Cache Dub packages
        uses: actions/cache@v3
        with:
          path: ~/.dub/packages
          key: dub-${{ runner.os }}-${{ matrix.dlang }}-${{ hashFiles('dub.selections.json') }}
          restore-keys: dub-${{ runner.os }}-${{ matrix.dlang }}-
      - name: Run tests
        run: dub test --coverage --coverage-ctfe
      - name: Lint sources
        run: dub lint
      - name: Verify coverage
        run: ./scripts/check_coverage.d
      - name: CLI smoke test
        run: dub run -- --dir source/lib --exclude-unittests --threshold=0.9 --min-lines=3
